input_files:
  - path: /pscratch/sd/n/nacc/training_data/era5_1980-2023_q2m-48H.zarr
    channel_in:
      - q2m-48H
  - path: /pscratch/sd/n/nacc/training_data/era5_1980-2023_z1000-48H.zarr
    channel_in:
      - z1000-48H
  - path: /pscratch/sd/n/nacc/training_data/hpx64_2000-2021_3h_dltm-v3.1.zarr
    channel_in:
      - swvl1
output_files:
  - path: /pscratch/sd/n/nacc/training_data/hpx64_2000-2021_3h_dltm-v3.1.zarr
    channel_out:
      - swvl1
constant_files:
  - path: /pscratch/sd/n/nacc/training_data/hpx64_2000-2021_3h_dltm-v3.1.zarr
    channel_c:
      - lsm
      - slt
time_subset_start: 2015-01-01T00:00:00
time_subset_end: 2015-02-28T21:00:00
time_subset_freq: 3h
output_file: /pscratch/sd/n/nacc/veggie-dltm/dlesym_pipeline/compilation/output/test_compilation.zarr
chunks:
  time: 1
overwrite: true