  # file with data to be imputed
- filename: ./processing/outputs/icesheet_mask_dev/maiac_0.25deg_HPX64_2001_NDVI_gapfill_mask-ice.nc
  variable: NDVI_gapfill  # variable in the file that needs imputation
  time_slice: 
    start: 2001-01-01T00:00:00  # start time for slicing the data
    end: 2001-02-01T00:00:00    # end time for slicing the data
  output_file_prefix: ./processing/outputs/var_meta_dev/var_meta_dev_ndvi  # output file prefix
  metas:
    - min
    - max
    - annual_range
  chunks:
    time: 256  # chunk size for processing the data
  overwrite: true  # whether to overwrite existing output file
  output_plot_dir: ./processing/outputs/var_meta_dev/plots_ndvi # output directory for plots
- filename: ./processing/outputs/icesheet_mask_dev/era5-land_0.25deg_HPX64_2001_swvl1_mask-ice.nc
  variable: swvl1  # variable in the file that needs imputation
  time_slice: 
    start: 2001-01-01T00:00:00  # start time for slicing the data
    end: 2001-02-01T00:00:00    # end time for slicing the data
  output_file_prefix: ./processing/outputs/var_meta_dev/var_meta_dev_swvl1  # output file prefix
  metas:
    - min
    - max
    - annual_range
  chunks:
    time: 256  # chunk size for processing the data
  overwrite: true  # whether to overwrite existing output file
  output_plot_dir: ./processing/outputs/var_meta_dev/plots_swvl1 # output directory for plots